### ISSUE TITLE
Shift + Left Click causes error

### ISSUE THREAD

**Issue by MikuAuahDark** [pfirsich/jprof#11]
```
Error: util.lua:69: attempt to index field 'pathCache' (a nil value)
stack traceback:
        [string "boot.lua"]:637: in function '__index'
        util.lua:69: in function 'getNodeByPath'
        draw.lua:354: in function 'draw'
        [string "boot.lua"]:513: in function <[string "boot.lua"]:493>
        [C]: in function 'xpcall'
```

Graph type is set to "time". That's all.

**Comment by pfirsich** [comment]
So I put a "fix" for this in the develop branch 9 days ago, which I pointed @MikuAuahDark to personally. My real problem with fixing this is that I am not quite sure what I want shift-click to do now. 

If you click on a zone when examining a single frame (e.g. the third occurence of "update" in the "update player" zone), then every frame you select from then on will draw a flame graph with the root node being the third occurence of "update" in the "update player" zone (i.e. the "node path" is the same). The graph at the bottom will only show the contributions of all zones with this node path and it's children too.

But if you then shift-click and select a region, what should it show? Previously averaged frame ranges didn't pay any attention to "the third occurence" of etc. All the "update" zones in the "update player" zone would be averaged together. Which I think is not a bad behaviour. The same problem but "from the other side" is: what happens when you select a zone of an averaged frame range? What does the graph show?

I think I have to change averaged frames so that they consider each node by it's node path (so not all "update"s in "update player" are average together). But I am not quite sure if that is really what I want this feature to do.

**Comment by pfirsich** [comment]
I can't just leave it like this, so I will fix it with averaging nodes by path. I think this is less useful as an average, but the only solution that makes sense in itself.
